---
# Ruby LSP configuration - fixed indexing while avoiding ERB formatting issues
enabledFeatures:
  - documentSymbols
  - foldingRanges
  - selectionRanges
  - completion
  - hover
  - definition
  - references
  - diagnostics

# Disable only formatting features to avoid ERB issues
disabledFeatures:
  - formatting
  - onTypeFormatting

# Index configuration - include Ruby files but exclude problematic patterns
indexing:
  includedPatterns:
    - "**/*.rb"
    - "**/*.rake"
    - "**/Rakefile"
    - "**/Gemfile"
  excludedPatterns:
    - "tmp/**/*"
    - "log/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - ".git/**/*"
    - "coverage/**/*"
    - ".ruby-lsp/**/*"

# Disable experimental features
experimentalFeaturesEnabled: false
